### ISSUE TITLE
[ds-view] Landing pages do not display correctly when their is >1 investigation for the bundle

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#4]
**Describe the bug**
From @rchenatjpl:

>    I'm not sure what repository to post this in. All these bundles have N lid_references to >1 separate investigation, but the Keyword Search just replicates the first investigation N times:
>
>    PPI's: https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Agaskell.phobos.shape-model&version=1.0

>    GEO's: https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Alunar-crust-magnetic.field-map&version=1.0

>    new GEO's: https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Aapollo_seismic_event_catalog&version=1.0

**Comment by jordanpadams** [comment]
@c-suh do you have some time to look at this for this sprint? or should we plan for next sprint?

**Comment by c-suh** [comment]
@jordanpadams next sprint, please, but I will definitely take a look before then if I get the chance.

**Comment by c-suh** [comment]
@rchenatjpl multiple investigations should now be listing correctly instead of repeating the 1st one N times. Give it a try and let me know if you see any problems. (I also got rid of the duplicate sub-menu. Let me know if you need to know the edit in case you generate more pages or use a template.)

---

@jordanpadams I pulled the code from our svn repository, but it's significantly outdated (version 1.0.12 versus the deployed's version 2.13.0). I made the fix directly to the relevant file but haven't been able to package it into a WAR, so, as you know, it'll be overwritten as soon as anybody redeploys the app. Where can I get the latest source code, please? You had mentioned that the various svn repos on starcell were going to be moved to GitHub, so I glanced through the repos in NASA-PDS but apologies if I missed them.

**Comment by jordanpadams** [comment]
@c-suh here you go! https://github.jpl.nasa.gov/PDSEN/pds4-java/tree/master/portal/ds-view

**Comment by jordanpadams** [comment]
sorry for the painfulness of having to jump around repos

**Comment by c-suh** [comment]
No worries and thank you! I'll have it pushed tomorrow

**Comment by rchenatjpl** [comment]
Looks good to me. Thanks, Catherine.

**Comment by c-suh** [comment]
Changes have been pushed and a pull request opened at https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/133, which also addresses https://github.com/NASA-PDS/PDS-Software-Issues-Repo/issues/5. However, I am having trouble packaging this into a war and have reached out to @jordanpadams for help.

**Comment by c-suh** [comment]
Packaging resolved in https://github.com/NASA-PDS/PDS-Software-Issues-Repo/issues/5#issuecomment-777890974 and war files dropped onto operational servers.

**Comment by c-suh** [comment]
@tloubrieu-jpl, @jordanpadams, or @rchenatjpl, if one of you would be so kind, I don't have the permissions to close this issue.
