### ISSUE TITLE
Refactor templates repo for detect secrets and distribute to all EN repos

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#55]
## 💡 Description

https://nasa-ammos.github.io/slim/continuous-integration/starter-kits/#git-secrets

Probably need discussion with secrets/credentials provider: https://github.com/awslabs/git-secrets#id20 

Should follow the guidelines and recommendations from here: https://github.com/NASA-AMMOS/slim/issues/89

**Comment by nutjob4life** [comment]
Hi @jordanpadams, in between the time this issue was created (Jan 17) and the time it was put onto the backlog (Oct 17), a major thing has changed over at [SLIM](https://nasa-ammos.github.io/slim/), that being: they no longer recommend [git-secrets](https://github.com/awslabs/git-secrets).

Instead, they've settled onto another tool, [detect-secrets](https://github.com/Yelp/detect-secrets), which they've [documented extensively](https://nasa-ammos.github.io/slim/docs/guides/software-lifecycle/security/secrets-detection/). It looks like detect-secrets can do a whole lot more than git-secrets, which worked fine for AWS keys. Yet detect-secrets can also find absolute file paths ([which you commented on](https://github.com/NASA-AMMOS/slim/issues/89#issuecomment-1432026841)), sensitive email addresses, hostnames—and even do entropy analysis (automatic detection of secrets based on their high degree of randomness).

We've already settled onto git-secrets for the [template-repo-python](https://github.com/NASA-PDS/template-repo-python/) and [template-repo-java](https://github.com/NASA-PDS/template-repo-java), and I can certainly spread git-secrets out to the rest of our repositories.

But, as the issue description says above ↑, do we want to follow the guidelines at [NASA-AMMOS/slim#89](https://github.com/NASA-AMMOS/slim/issues/89)—which would mean going to detect-secrets—or do what the issue title says—which would be propagating git-secrets?

**Comment by jordanpadams** [comment]
@nutjob4life feel free to refactor all this towards the best solution you deem for our projects. in this case, let's role with detect-secrets.

**Comment by nutjob4life** [comment]
To resolve this, I need to use [the sandbox](https://github.com/nasa-pds-engineering-node), however I have a prerequisite [pull request](https://github.com/NASA-PDS/roundup-action/pull/126) that'll need to be merged so I can get the sandbox working again.

**Comment by nutjob4life** [comment]
Notes to self.

### Gathering the Tools

All developers—whether they use Python or Java—will need Python. (Honestly, I'm not sure how I feel about this.)

One quickie idea:
```console
$ cd $HOME
$ python3 -m venv bin
$ cat > bin/requirements.txt <<EOF
pre-commit ~= 3.5.0
detect-secrets @ git+https://github.com/NASA-AMMOS/slim-detect-secrets.git@exp
EOF
$ bin/pip3 install --requirement bin/requirements.txt
```

### Establishing the Baseline

To generate the baseline of PDS repositories, we'll need to exclude far more than the SLIM folk think, as we don't commit generated files (I hope they aren't either).

#### For Python
```
detect-secrets scan . \
    --all-files \
    --disable-plugin AbsolutePathDetectorExperimental \
    --exclude-files '\.secrets..*' \
    --exclude-files '\.git.*' \
    --exclude-files '\.mypy_cache' \
    --exclude-files '\.pytest_cache' \
    --exclude-files '\.tox' \
    --exclude-files '\.venv' \
    --exclude-files 'venv' \
    --exclude-files 'dist' \
    --exclude-files 'build' \
    --exclude-files '.*\.egg-info' > .secrets.baseline
```
#### For Maven
```
detect-secrets scan . \
    --all-files \
    --disable-plugin AbsolutePathDetectorExperimental \
    --exclude-files '\.secrets..*' \
    --exclude-files '\.git.*' \
    --exclude-files 'target' > .secrets.baseline
```

**Comment by nutjob4life** [comment]
Progress: this is now functioning in the sandbox's `pds-template-repo-python`. Next step is to try it in the sandbox `pds-template-repo-java` and then see if we want to roll it out everywhere, and update our various instructions.

(Still have an open question about whether we want to force Java developers to install Python.)

**Comment by nutjob4life** [comment]
Progress: this is now functioning in the sandbox's `pds-template-repo-java`.

I've also updated the READMEs for both Java and Python with instructions on how to use `detect-secrets`. These instructions reference a wiki page that is yet to be written, so these are the next steps:

1. Write the wiki page so the links from the READMEs aren't 404
2. Create PRs for these changes from the sandbox → the real NASA-PDS organization
3. Once approved, roll out all these changes to the rest of the NASA-PDS repositories

**Comment by nutjob4life** [comment]
Suggested repositories:

- archive-viewer
- data-upload-manager
- deep-archive
- doi-service
- doi-ui
- ds-view
- harvest
- lasso-issues
- mi-label
- nucleus
- pds-api
- pds-api-client
- pds3-product-tools
- pds4-jparser
- pdsen-maven-parent
- registry
- registry-api
- registry-common
- registry-crawler-service
- registry-dashboards
- registry-harvest-cli
- registry-harvest-legacy
- registry-harvest-service
- registry-loader
- registry-mgr
- registry-mgr-legacy
- registry-pds3-catalog
- registry-sweepers
- roundup-action
- search-ui-legacy
- transform
- validate

**Comment by nutjob4life** [comment]
Suggested repositories:

- [x] [archive-viewer](https://github.com/NASA-PDS/archive-viewer)
- [x] [data-upload-manager](https://github.com/NASA-PDS/data-upload-manager)
- [x] [deep-archive](https://github.com/NASA-PDS/deep-archive)
- [x] [doi-service](https://github.com/NASA-PDS/doi-service)
- [x] [doi-ui](https://github.com/NASA-PDS/doi-ui)
- [x] [ds-view](https://github.com/NASA-PDS/ds-view)
- [x] [harvest](https://github.com/NASA-PDS/harvest)
- [x] [lasso-issues](https://github.com/NASA-PDS/lasso-issues)
- [x] [mi-label](https://github.com/NASA-PDS/mi-label)
- [x] [nucleus](https://github.com/NASA-PDS/nucleus)
- [x] [pds-api](https://github.com/NASA-PDS/pds-api)
- [x] [pds-api-client](https://github.com/NASA-PDS/pds-api-client)
- [x] [pds3-product-tools](https://github.com/NASA-PDS/pds3-product-tools)
- [x] [pds4-jparser](https://github.com/NASA-PDS/pds4-jparser)
- [x] [pdsen-maven-parent](https://github.com/NASA-PDS/pdsen-maven-parent)
- [x] [registry](https://github.com/NASA-PDS/registry)
- [x] [registry-api](https://github.com/NASA-PDS/registry-api)
- [x] [registry-common](https://github.com/NASA-PDS/registry-common)
- [x] [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service)
- [x] [registry-dashboards](https://github.com/NASA-PDS/registry-dashboards)
- [x] [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli)
- [x] [registry-harvest-legacy](https://github.com/NASA-PDS/registry-harvest-legacy)
- [x] [registry-harvest-service](https://github.com/NASA-PDS/registry-harvest-service)
- [x] [registry-loader](https://github.com/NASA-PDS/registry-loader)
- [x] [registry-mgr](https://github.com/NASA-PDS/registry-mgr)
- [x] [registry-mgr-legacy](https://github.com/NASA-PDS/registry-mgr-legacy)
- [x] [registry-pds3-catalog](https://github.com/NASA-PDS/registry-pds3-catalog)
- [x] [registry-sweepers](https://github.com/NASA-PDS/registry-sweepers)
- [x] [roundup-action](https://github.com/NASA-PDS/roundup-action)
- [x] [search-ui-legacy](https://github.com/NASA-PDS/search-ui-legacy)
- [x] [transform](https://github.com/NASA-PDS/transform)
- [x] [validate](https://github.com/NASA-PDS/validate)

**Comment by tloubrieu-jpl** [comment]
@nutjob4life is investigating 4 repos which do not behave as expected. The others are good.

**Comment by nutjob4life** [comment]
It turns out it was _three_ repositories, not _four_, that had problems with server-side secrets-detection via GitHub Actions.

Only [one of those repositories](https://github.com/NASA-PDS/deep-archive) got merged into `main`, so I've filed [a fresh pull request](https://github.com/NASA-PDS/deep-archive/pull/154) to fix the problem with the server-side secrets detection.

The other two repositories, [`doi-ui`](https://github.com/NASA-PDS/doi-ui/) and [`registry`](https://github.com/NASA-PDS/registry), had their pull requests remain open. So I've pushed additional commits to those branches to address the problems with server-side secrets detection.

The `doi-ui` PR has already been merged, leaving (at the time of this writing), the [PR for secrets on `registry` open](https://github.com/NASA-PDS/registry/pull/246).

In addition, these PRs for secrets detection remain open at the time of this writing—but had no issues with their secrets-detection status checks in GitHub Actions:

- https://github.com/NASA-PDS/roundup-action/pull/129
- https://github.com/NASA-PDS/search-ui-legacy/pull/4
- https://github.com/NASA-PDS/validate/pull/770

**Comment by jordanpadams** [comment]
@nutjob4life one more I found: https://github.com/NASA-PDS/wds-react-legacy/tree/main/.github/workflows

**Comment by nutjob4life** [comment]
@jordanpadams [pull request created](https://github.com/NASA-PDS/wds-react-legacy/pull/172)

**Comment by jordanpadams** [comment]
Closing this out since most repos have been retrofitted. Will add to additional repos as needed if any were missed.
